### ISSUE TITLE
Update 1.5.0 - Login error

### ISSUE THREAD

**Issue by jbr1989** [MaxWaldorf/guacamole#53]
I had update docker container to version 1.5.0.

Now, I can't enter in my control panel, because the login not working with previuous data.

I've investigated and there seems to be a problem with the guacamole program.
It seems that the connection to the database is broken.

Any solutions?

**Comment by MaxWaldorf** [comment]
Yes while it was working on my last compile, it seems the script is calling postgres with root user which cannot work...

**Comment by carfanatic93** [comment]
Same problem here. No login after update to 1.5.0

**Comment by fate8383** [comment]
> Yes while it was working on my last compile, it seems the script is calling postgres with root user which cannot work...

Hi, does this mean issue is resolved now? I used 1.4.3 tag so it is workin again but I would like to use the latest, not sure based on the last three tickets this issue is resolved.

**Comment by MaxWaldorf** [comment]
give me some time to review the code and why it is not working...
I'm doing that on my free time...

**Comment by Mitch187** [comment]
I put the complete log in an extra threat. For your  help.
After that, i see the posting here.

**Comment by MaxWaldorf** [comment]
please re-dowload 1.5.0

works here

**Comment by johan-NL** [comment]
Still doesn't work. Tried building with and without EXTENSIONS = auth-totp,auth-duo and with. Same result, guacadmin/guacadmin does not gets accepted.

**Comment by MaxWaldorf** [comment]
For now, try to use the 1.4.0 image register a user and then migrate to 1.5.0

The S6 framework is giving me headaches, I am working on replacing it...

**Comment by Bolex80** [comment]
Hi,
I tried using version 1.4.0, but there is some issue with your postgress. In the logs I get this all the time:
Waiting for postgres to come up...
Starting postgres...
s6-applyuidgid: fatal: unable to exec postgres: No such file or directory
/var/run/postgresql:5432 - no response

If I use the "latest" container, these are the logs:

Starting postgres...
2023-03-18 09:56:35.460 UTC [714] LOG:  invalid value for parameter "lc_messages": "en_US.UTF-8"
2023-03-18 09:56:35.460 UTC [714] LOG:  invalid value for parameter "lc_monetary": "en_US.UTF-8"
2023-03-18 09:56:35.460 UTC [714] LOG:  invalid value for parameter "lc_numeric": "en_US.UTF-8"
2023-03-18 09:56:35.460 UTC [714] LOG:  invalid value for parameter "lc_time": "en_US.UTF-8"
2023-03-18 09:56:35.460 UTC [714] FATAL:  configuration file "/config/postgres/postgresql.conf" contains errors
/var/run/postgresql:5432 - no response

**Comment by Mitch187** [comment]
I have download a new version, but it does not work too:

` Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in the request target [/#login ]. The valid characters are defined in RFC 7230 and RFC 3986
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:517)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:513)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:882)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1693)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
18-Mar-2023 08:27:30.370 INFO [http-nio-8080-exec-5] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP request parsing errors will be logged at DEBUG level.
	java.lang.IllegalArgumentException: Invalid character found in the request target [/#/login ]. The valid characters are defined in RFC 7230 and RFC 3986
		at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:517)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:513)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:882)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1693)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:750)
09:12:08.856 [http-nio-8080-exec-10] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from [35.242.254.56, 192.168.15.5] for user "guacadmin" failed.
09:12:09.041 [http-nio-8080-exec-2] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from [35.242.254.56, 192.168.15.5] for user "guacadmin" failed.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 30-defaults.sh: executing... 
[cont-init.d] 30-defaults.sh: exited 0.
[cont-init.d] 40-postgres.sh: executing... 
Database already configured
[cont-init.d] 40-postgres.sh: exited 0.
[cont-init.d] 50-extensions: executing... 
[cont-init.d] 50-extensions: exited 0.
[cont-init.d] done.
[services.d] starting services
Starting guacamole guacd...
Starting postgres...
[services.d] done.
/var/run/postgresql:5432 - no response
Waiting for postgres to come up...
guacd[272]: INFO:	Guacamole proxy daemon (guacd) version 1.5.0 started
guacd[272]: INFO:	Listening on host 0.0.0.0, port 4822
2023-03-18 11:53:50.554 UTC [273] LOG:  starting PostgreSQL 13.9 (Debian 13.9-0+deb11u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
2023-03-18 11:53:50.555 UTC [273] LOG:  listening on IPv4 address "127.0.0.1", port 5432
2023-03-18 11:53:50.555 UTC [273] LOG:  could not bind IPv6 address "::1": Cannot assign requested address
2023-03-18 11:53:50.555 UTC [273] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
2023-03-18 11:53:50.559 UTC [273] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-03-18 11:53:50.571 UTC [282] LOG:  database system was interrupted; last known up at 2023-03-18 07:58:43 UTC
2023-03-18 11:53:50.864 UTC [282] LOG:  database system was not properly shut down; automatic recovery in progress
2023-03-18 11:53:50.871 UTC [282] LOG:  redo starts at 0/173CA88
2023-03-18 11:53:50.871 UTC [282] LOG:  invalid record length at 0/173CAC0: wanted 24, got 0
2023-03-18 11:53:50.871 UTC [282] LOG:  redo done at 0/173CA88
2023-03-18 11:53:50.899 UTC [273] LOG:  database system is ready to accept connections
2023-03-18 11:53:51.510 UTC [290] FATAL:  role "root" does not exist
/var/run/postgresql:5432 - accepting connections
Starting guacamole client...
18-Mar-2023 11:53:52.085 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.82
18-Mar-2023 11:53:52.087 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Aug 8 2022 21:26:07 UTC
18-Mar-2023 11:53:52.087 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version number: 8.5.82.0
18-Mar-2023 11:53:52.087 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
18-Mar-2023 11:53:52.087 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            5.15.85-1-pve
18-Mar-2023 11:53:52.087 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
18-Mar-2023 11:53:52.088 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-8/jre
18-Mar-2023 11:53:52.088 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_342-b07
18-Mar-2023 11:53:52.088 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
18-Mar-2023 11:53:52.088 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
18-Mar-2023 11:53:52.088 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
18-Mar-2023 11:53:52.088 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
18-Mar-2023 11:53:52.088 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
18-Mar-2023 11:53:52.089 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
18-Mar-2023 11:53:52.089 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
18-Mar-2023 11:53:52.089 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
18-Mar-2023 11:53:52.089 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
18-Mar-2023 11:53:52.089 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
18-Mar-2023 11:53:52.089 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
18-Mar-2023 11:53:52.090 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
18-Mar-2023 11:53:52.090 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded Apache Tomcat Native library [1.2.35] using APR version [1.7.0].
18-Mar-2023 11:53:52.090 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true], UDS [{4}].
18-Mar-2023 11:53:52.090 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
18-Mar-2023 11:53:52.093 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1n  15 Mar 2022]
18-Mar-2023 11:53:52.168 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
18-Mar-2023 11:53:52.186 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 498 ms
18-Mar-2023 11:53:52.220 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
18-Mar-2023 11:53:52.221 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet engine: [Apache Tomcat/8.5.82]
18-Mar-2023 11:53:52.250 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ROOT.war]
18-Mar-2023 11:53:53.647 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
11:53:54.152 [localhost-startStop-1] INFO  o.a.g.environment.LocalEnvironment - GUACAMOLE_HOME is "/config/guacamole".
11:53:54.276 [localhost-startStop-1] INFO  o.a.g.GuacamoleServletContextListener - Read configuration parameters from "/config/guacamole/guacamole.properties".
11:53:54.279 [localhost-startStop-1] INFO  o.a.g.rest.auth.HashTokenSessionMap - Sessions will expire after 60 minutes of inactivity.
11:53:54.711 [localhost-startStop-1] INFO  o.a.g.t.w.WebSocketTunnelModule - Loading JSR-356 WebSocket support...
18-Mar-2023 11:53:55.764 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ROOT.war] has finished in [3,514] ms
18-Mar-2023 11:53:55.766 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
18-Mar-2023 11:53:55.777 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 3590 ms
11:54:24.095 [http-nio-8080-exec-10] WARN  o.a.g.r.auth.AuthenticationService - Authentication attempt from [37.201.221.64, 192.168.15.5] for user "guacadmin" failed.`

**Comment by Mitch187** [comment]
I go back to 1.4.3 and it works. Please write here, when i can start an update again.

**Comment by MaxWaldorf** [comment]
I have an image in build...
1.5.0 should be back out soon again...

**Comment by fate8383** [comment]
> I have an image in build...
> 1.5.0 should be back out soon again...

is it the nightly tag? it seems updated 8 hours ago or not yet there?

**Comment by MaxWaldorf** [comment]
should available now...

**Comment by carfanatic93** [comment]
> should be available now...
Unfortunately it doesn't work...
![image](https://user-images.githubusercontent.com/128144210/226469128-1d6ff257-97a6-4c79-8dda-92f58b241cb4.jpeg)![image](https://user-images.githubusercontent.com/128144210/226469157-27665ba9-92c5-4ca5-a382-ac39508100df.jpeg)

**Comment by fate8383** [comment]
still failing with fatal error

2023-03-20 21:28:44.930 UTC [41] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
29
2023-03-20 21:28:45.266 UTC [84] LOG:  database system was interrupted; last known up at 2023-03-20 17:16:09 UTC
30
2023-03-20 21:28:45.997 UTC [86] FATAL:  the database system is starting up
31
/var/run/postgresql:5432 - rejecting connections
32
Waiting for postgres to come up...
33
2023-03-20 21:28:47.008 UTC [89] FATAL:  the database system is starting up
34
/var/run/postgresql:5432 - rejecting connections
35
Waiting for postgres to come up...
36
2023-03-20 21:28:48.034 UTC [92] FATAL:  the database system is starting up
37
/var/run/postgresql:5432 - rejecting connections
38
Waiting for postgres to come up...
39
2023-03-20 21:28:49.047 UTC [95] FATAL:  the database system is starting up
40
/var/run/postgresql:5432 - rejecting connections
41
Waiting for postgres to come up...
42
2023-03-20 21:28:50.099 UTC [98] FATAL:  the database system is starting up
43
/var/run/postgresql:5432 - rejecting connections
44
Waiting for postgres to come up...

**Comment by carfanatic93** [comment]
I confirm that a fresh install works

**Comment by ovizii** [comment]
Hi guys, 
I just wanted to ask, was the problem identified and fixed? I can see that people confirm that a fresh install works, does this mean there is no upgrade path except a fresh install? 

Not complaining, just trying to figure out what the status is. 

I tried reading the changelog to see if there is anything that could have broken from Guac's side: https://guacamole.apache.org/releases/1.5.0/#changelog but I can't spot anything except maybe for the latest PostgreSQL JDBC driver.

**Comment by MaxWaldorf** [comment]
My server works with 1.5.0 and I have it running since 1.3.0

I really don't understand (no time to investigate) why some fail...

**Comment by fate8383** [comment]
fresh install works, however when compose stoped and restarted always generating quite a lot of these errors. eventually starts anyway...


2023-03-21 10:15:46.333 UTC [102] ERROR:  duplicate key value violates unique constraint "guacamole_user_permission_pkey"
584
2023-03-21 10:15:46.333 UTC [102] DETAIL:  Key (entity_id, affected_user_id, permission)=(1, 1, READ) already exists.
585
2023-03-21 10:15:46.333 UTC [102] STATEMENT:  INSERT INTO guacamole_user_permission (entity_id, affected_user_id, permission)
586
	SELECT guacamole_entity.entity_id, guacamole_user.user_id, permission::guacamole_object_permission_type
587
	FROM (
588
	    VALUES
589
	        ('guacadmin', 'guacadmin', 'READ'),
590
	        ('guacadmin', 'guacadmin', 'UPDATE'),
591
	        ('guacadmin', 'guacadmin', 'ADMINISTER')
592
	) permissions (username, affected_username, permission)
593
	JOIN guacamole_entity          ON permissions.username = guacamole_entity.name AND guacamole_entity.type = 'USER'
594
	JOIN guacamole_entity affected ON permissions.affected_username = affected.name AND guacamole_entity.type = 'USER'
595
	JOIN guacamole_user            ON guacamole_user.entity_id = affected.entity_id;
596
psql:<stdin>:791: ERROR:  duplicate key value violates unique constraint "guacamole_user_permission_pkey"
597
DETAIL:  Key (entity_id, affected_user_id, permission)=(1, 1, READ) already exists.

**Comment by MaxWaldorf** [comment]
use the env...
Don't use the file... it doesn't work... and has never worked... (not designed that way)

**Comment by fate8383** [comment]
I am using the env for extension to be enabled but I have to use toto-issuer tag name in the properties since I have multiple instances and identify them in the authenticator app. is there a way to do this also in env? properties edit is working in the 1.4.3
I just killed Postgres in container, stopped compose and restarted and it is again working with totp enabled but still has this error https://github.com/MaxWaldorf/guacamole/issues/53#issuecomment-1477582381

**Comment by fate8383** [comment]
as suspected also server reboot or docker reboot errors out and not starting, I guess I will stick with 1.4.3 for now definitely some postgres integration issue but also cannot troubleshoot further:

PostgreSQL Database directory appears to contain a database; Skipping initialization
615
616
2023-03-21 11:28:38.260 UTC [41] FATAL:  lock file "postmaster.pid" already exists
617
2023-03-21 11:28:38.260 UTC [41] HINT:  Is another postmaster (PID 38) running in data directory "/config/postgres"?
618
/var/run/postgresql:5432 - no response
619
Waiting for postgres to come up...
620
/var/run/postgresql:5432 - no response
621
Waiting for postgres to come up...

**Comment by Bolex80** [comment]
> Very strange, Have you stopped compose and started again? I have tons of logs I shared above comments not sure what is up with my clean install. It works like a charm as fresh then restarts makes all go side ways...
> 
> > With Clean install and using docker-compose it is working like a charm for me. (v.1.5.0)
> > Thank you for your effort and hard work!

Yes I did restart it. I created a plain docker-compose and actually deployed it via  stacks in portainer.
Once I was able to log in, I then recreated it to add TOTP AUTH As an environment.
still working so far. 
Let me know if you need the exact steps and docker-compose I used. (but it will be later, not home now to get into portainer).

**Comment by fate8383** [comment]
> > Very strange, Have you stopped compose and started again? I have tons of logs I shared above comments not sure what is up with my clean install. It works like a charm as fresh then restarts makes all go side ways...
> 
> > 
> 
> > > With Clean install and using docker-compose it is working like a charm for me. (v.1.5.0)
> 
> > > Thank you for your effort and hard work!
> 
> 
> 
> Yes I did restart it. I created a plain docker-compose and actually deployed it via  stacks in portainer.
> 
> Once I was able to log in, I then recreated it to add TOTP AUTH As an environment.
> 
> still working so far. 
> 
> Let me know if you need the exact steps and docker-compose I used. (but it will be later, not home now to get into portainer). 
> 
> 

I am doing exactly the same, portainer stack with totp... could you please check guacamole container logs in portainer? After restart the stack? You have no postgres error at all? I am eventually getting all working in the front end but tons of error in the logs. After restart docker or server the same errors and eventually starts. Maybe we can share config to compare :) I am puzzled how flawless 1.4.3 works and 1.5 throws many errors and eventually works

**Comment by MaxWaldorf** [comment]
please try the testing tag in an hour from now when the build will finish...
I hope this one fixes issues...

**Comment by fate8383** [comment]
> please try the testing tag in an hour from now when the build will finish...
> I hope this one fixes issues...

Fantastic! testing tag is working very well with all the above issues I have tested. I think ready as a latest tag. Thanks a lot! what was the issue with the Postgres? just out of curiosity.

**Comment by MaxWaldorf** [comment]
1.5.0 update in progress...

**Comment by rtorchia** [comment]
I was having issues with the original 1.5 release with logins, but this latest one working great!
Using Portainer, I have a stack, and I just did a "update the stack", and it is running like a champ!

**Comment by MaxWaldorf** [comment]
new 1.5.0 image coming up...
this time, we should be good for a while!

**Comment by fate8383** [comment]
> new 1.5.0 image coming up...
> 
> this time, we should be good for a while!

Fresh install or update? Which one you recommend? Already on 1.5

**Comment by MaxWaldorf** [comment]
update should be fine (tested on my end)

**Comment by fate8383** [comment]
> update should be fine (tested on my end)

Update fails the Totp, not accepting my code....all else is working. I guess I need to do fresh again

**Comment by MaxWaldorf** [comment]
works here since 1.3.0

**Comment by fate8383** [comment]
> works here since 1.3.0

Cannot even do fresh, totp code is not accepted even complete fresh. Changed via -e time zone but no success. Disabled totp, all works fine but not with totp. I suspect this is a timezone issue. Postgres always on utc based and guacamole is taking user -e time zone but even running utc on guacamole is not solving the problem. Strange issue really.
